//go:build linux

// Sample output:
//
// sudo ./sockfilter -i eth0
// interface: eth0 protocol: ICMP  8.8.8.8:0(src) -> 10.112.62.185:7042(dst)                                                                                                             │
// interface: eth0 protocol: ICMP  8.8.8.8:0(src) -> 10.112.62.185:47409(dst)

package main

import (
	"bytes"
	"encoding/binary"
	"errors"
	"github.com/cilium/ebpf/internal"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"
	flag "github.com/spf13/pflag"
	"log"
	"net"
	"os"
	"os/signal"
	"syscall"
)

//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -tags "linux" -type event bpf sockfilter.c -- -I../headers

type Config struct {
	Iface string
}

var (
	config Config
)

const (
	LOOP = 1
)

func main() {

	// Config.Iface = "lo"
	flag.StringVarP(&config.Iface, "interface", "i", "lo", "interface to capture")

	stopper := make(chan os.Signal, 1)
	signal.Notify(stopper, os.Interrupt, syscall.SIGTERM)

	// Allow the current process to lock memory for eBPF resources.
	if err := rlimit.RemoveMemlock(); err != nil {
		log.Fatal(err)
	}

	conn, err := net.ListenTCP("tcp", &net.TCPAddr{IP: net.IPv4(127, 0, 0, 1)})
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close()

	// Load pre-compiled programs and maps into the kernel.
	objs := bpfObjects{}
	if err = loadBpfObjects(&objs, nil); err != nil {
		log.Fatalf("loading objects: %v", err)
	}
	defer objs.Close()

	// Attach ebpf program to a socket
	err = link.AttachSocketFilter(conn, objs.bpfPrograms.BpfSocketHandler)
	if err != nil {
		log.Fatal(err)
	}

	log.Printf("eBPF program loaded and attached on socket")

	rd, err := ringbuf.NewReader(objs.bpfMaps.Rb)
	if err != nil {
		log.Fatalf("opening ringbuf reader: %s", err)
	}
	defer rd.Close()

	log.Printf("%-15s %-6s -> %-15s %-6s %-6s",
		"interface",
		"protocol",
		"src",
		"->",
		"dst",
	)
	go readLoop(rd)

	// Wait
	<-stopper
}

func readLoop(rd *ringbuf.Reader) {
	// bpfEvent is generated by bpf2go.
	var event bpfEvent
	for {
		record, err := rd.Read()
		if err != nil {
			if errors.Is(err, ringbuf.ErrClosed) {
				log.Println("received signal, exiting..")
				return
			}
			log.Printf("reading from reader: %s", err)
			continue
		}

		// Parse the ringbuf event entry into a bpfEvent structure.
		if err := binary.Read(bytes.NewBuffer(record.RawSample), internal.NativeEndian, &event); err != nil {
			log.Printf("parsing ringbuf event: %s", err)
			continue
		}

		log.Printf("%-6d  %-6d %-15s %-6s -> %-15s %-6d",
			event.Ifindex,
			event.IpProto,
			intToIP(event.SrcAddr),
			event.Ports,
			intToIP(event.DstAddr),
			//event.Dport,
		)
	}
}

// intToIP converts IPv4 number to net.IP
func intToIP(ipNum uint32) net.IP {
	ip := make(net.IP, 4)
	binary.BigEndian.PutUint32(ip, ipNum)
	return ip
}
